name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred version

      - name: Upgrade npm
        run: npm install npm@latest

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove package-lock and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install dependencies with retry and force
        run: |
          for i in 1 2 3; do
            npm install --legacy-peer-deps --force && break
            echo "Retrying npm install ($i)..."
            sleep 5
          done

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
